set guioptions-=T
set guifont=Monaco:h12
set lines=52
set columns=170

" Possibly kill the scrollbar
set guioptions=aAce

" Set transparency (possibly experimental renderer is reuqired)
" set transp=95
