set guioptions-=T
" set guifont=Monaco:h12
set guifont=Menlo:h14
set lines=35
set columns=90

" Copy register into system buffer, use console dialogs, disable scrollbar
set guioptions=aAce

" Precede the tab name with its number
set guitablabel=%N\ %t

colorscheme ir_black

" Set transparency (possibly experimental renderer is reuqired)
" set transp=95
