" @todo - yankring, fugitive, rubydo, \v in regexps
"
set guioptions-=T
" set guifont=Monaco:h12
" set guifont=Menlo:h14
set guifont=Inconsolata:h15
set lines=35
set columns=90

" Copy register into system buffer, use console dialogs, disable scrollbar
set guioptions=aAce

" Precede the tab name with its number
set guitablabel=%N\ %t

" colorscheme ir_black

" Set transparency (possibly experimental renderer is required)
" set transp=95

" set relativenumber
set number
set scrolloff=3
set cursorline

" Autosave when MacVim loses focus
au FocusLost * silent! wa

function! Medio()
  set lines=55
  set columns=130
endfunction

function! Grande()
  set lines=49
  set columns=179
endfunction

function! Maximo()
  set lines=1000
  set columns=1000
endfunction

